services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/frigate/config:/config
      - /storage/config/config.yml:/config/config.yml:ro
      - /storage/frigate/media:/media/frigate
      - /storage/frigate/media/clips:/media/frigate/clips
      - /storage/frigate/media/recordings:/media/frigate/recordings
      - /storage/frigate/media/exports:/media/frigate/exports
      - /storage/frigate/media/tmp/cache:/tmp/cache
      - /storage/frigate/media/frigate:/db
      - type: tmpfs # 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000" # Port used by the Web UI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
